---
name: Build - Adapters on HW - Reusable

on:
  workflow_call:
    inputs:
      adapter_name:
        required: true
        type: string
      other_adapter_name:
        required: false
        type: string
        default: ""
      runner_name:
        required: true
        type: string
      platform:
        description: "Platform string, `UR_CTS_ADAPTER_PLATFORM` will be set to this."
        required: false
        type: string
        default: ""
      static_loader:
        required: false
        type: string
        default: OFF
      static_adapter:
        required: false
        type: string
        default: OFF

permissions:
  contents: read

env:
  UR_LOG_CUDA: "level:error;flush:error"
  UR_LOG_HIP: "level:error;flush:error"
  UR_LOG_LEVEL_ZERO: "level:error;flush:error"
  UR_LOG_NATIVE_CPU: "level:error;flush:error"
  UR_LOG_OPENCL: "level:error;flush:error"

jobs:
  adapter-build-hw:
    name: Build & Test HW
    if: github.repository == 'oneapi-src/unified-runtime'  # run only on upstream; forks won't have the HW
    strategy:
      matrix:
        adapter: [{
          name: "${{inputs.adapter_name}}",
          other_name: "${{inputs.other_adapter_name}}",
          platform: "${{inputs.platform}}",
          static_Loader: "${{inputs.static_loader}}",
          static_adapter: "${{inputs.static_loader}}"
        }]
        build_type: [Debug, Release]
        compiler: [{c: clang, cxx: clang++}]
        # TODO: The latest L0 loader segfaults when built with clang.
        exclude:
         - adapter: {name: L0, platform: ""}
           compiler: {c: clang, cxx: clang++}
        # Exclude these configurations to avoid overloading the runners.
         - adapter: {static_Loader: ON}
           build_type: Release
         - adapter: {static_Loader: ON}
           compiler: {c: clang, cxx: clang++}
         - adapter: {static_adapter: ON}
           build_type: Release
         - adapter: {static_adapter: ON}
           compiler: {c: clang, cxx: clang++}

    runs-on: ${{inputs.runner_name}}

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Target Build
      run: |
        BUILDDIR=build2
        mkdir build2
        if [ "$(pwd)" = /home/test-user/actions-runner/_work/unified-runtime/unified-runtime ]; then
          mkdir shared
          mv testfile.cpp source include build2 shared
          cd shared
        fi;
        /usr/bin/clang++ -DUR_ENABLE_SANITIZER -DUR_ENABLE_TRACING -DUR_VALIDATION_LAYER_SUPPORTED_VERSION="0" -DUR_VERSION="0" -D_FORTIFY_SOURCE=2 -Isource/common -Iinclude -g -Wall -Wpedantic -Wempty-body -Wformat -Wformat-security -Wunused-parameter -fPIC -fstack-protector-strong -fvisibility=hidden -flto -fsanitize=cfi -fno-sanitize=cfi-icall -fdebug-default-version=4 -fcf-protection=full -fstack-clash-protection -fcolor-diagnostics -Werror -Wextra -std=gnu++17 -MD -o ${BUILDDIR}/testfile.cpp.o -c testfile.cpp
        /usr/bin/clang++ -DUR_ENABLE_SANITIZER -DUR_ENABLE_TRACING -DUR_VALIDATION_LAYER_SUPPORTED_VERSION="0" -DUR_VERSION="0" -D_FORTIFY_SOURCE=2 -Isource/common -Iinclude -g -Wall -Wpedantic -Wempty-body -Wformat -Wformat-security -Wunused-parameter -fPIC -fstack-protector-strong -fvisibility=hidden -flto -fsanitize=cfi -fno-sanitize=cfi-icall -fdebug-default-version=4 -fcf-protection=full -fstack-clash-protection -fcolor-diagnostics -Werror -Wextra -std=gnu++17 -MD -o ${BUILDDIR}/ur_util.cpp.o -c source/common/ur_util.cpp
        /usr/bin/ar qc ${BUILDDIR}/libur_common.a ${BUILDDIR}/ur_util.cpp.o ${BUILDDIR}/testfile.cpp.o | tee ${BUILDDIR}/arlog

        md5sum ${BUILDDIR}/*
        echo "testfile: "
        base64 ${BUILDDIR}/testfile.cpp.o
        echo "ur_util: "
        base64 ${BUILDDIR}/ur_util.cpp.o

        test ! -s ${BUILDDIR}/arlog

    - name: Get information about platform
      if: ${{ always() }}
      run: .github/scripts/get_system_info.sh
