name: Build and test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  ncpu-at-cuda-1:
    name: N. Cpu @ Cuda 1
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-2:
    name: N. Cpu @ Cuda 2
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-3:
    name: N. Cpu @ Cuda 3
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-4:
    name: N. Cpu @ Cuda 4
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-5:
    name: N. Cpu @ Cuda 5
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-6:
    name: N. Cpu @ Cuda 6
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-7:
    name: N. Cpu @ Cuda 7
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-8:
    name: N. Cpu @ Cuda 8
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
  ncpu-at-cuda-9:
    name: N. Cpu @ Cuda 9
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: NATIVE_CPU
      runner_name: CUDA
