---
name: SYCL E2E

# The e2e workflow adds a comment to the pull request in the final step which
# requires the pull-request: write permission.
# When a pull request originates from a fork using the pull_request trigger
# will never grant write permissions due to security concerns.
# Instead, the pull_request_target trigger is necessary to be granted the
# pull-request: write permission.
on: [push, pull_request_target]

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-level-zero:
    name: E2E L0
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/e2e_level_zero.yml

  e2e-opencl:
    name: E2E OpenCL
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/e2e_opencl.yml

  e2e-cuda:
    name: E2E CUDA
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/e2e_cuda.yml
