name: E2E OpenCL

on:
  schedule:
    # Run every day at 23:00 UTC
    - cron: '0 23 * * *'
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-build-hw:
    # trigger only if PR comment contains "e2e-opencl"
    if: ${{ (github.event.issue.pull_request && contains(github.event.comment.body, '/e2e-opencl')) || (github.event_name == 'schedule') }}
    name: Start e2e job
    # use core flow, run it with OpenCL specific parameters
    uses: ./.github/workflows/e2e_core.yml
    # parameters that we pass to the core flow
    with:
      name: "OPENCL"
      runner_tag: "OPENCL"
      str_name: "opencl"
      prefix: ""
      config: ""
      unit: "cpu"
      trigger: "${{github.event_name}}"
