# Automatically add labels to pull requests based on globs in the
# .github/labeler.yml config file. For documentation see:
# https://github.com/marketplace/actions/labeler
---
name: Pull Request Labeler

on: [ pull_request_target ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
