name: Warn about intel/llvm migration

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

permissions:
  pull-requests: write
  issues: read

jobs:
  label-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Label and comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            const label = "auto-close";
            
            // Get current labels on the PR
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number: pr_number
            });

            // Check if label is already present
            if (!labels.some(labelObj => labelObj.name === label)) {
              // Add the label if not present
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: pr_number,
                labels: [label]
              });

              // Add a comment about the migration process and warn the PR will be automatically closed
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr_number,
                body: `This PR has been labelled with `${label}`. 
                <info about migration>
                It will be closed automatically in 30 days.`
              });

              console.log(`Added label '${label}' and commented on PR #${pr_number}`);
            } else {
              console.log(`PR #${pr_number} already has the '${label}' label. Skipping.`);
            }
